<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="itext.kernel.core" Version="1.0.2" />
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.9" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="Qdrant.Client" Version="1.15.1" />
    <PackageReference Include="QuestPDF" Version="2025.7.1" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.Json" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.Application\App.Application.csproj" />
    <ProjectReference Include="..\App.Common\App.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Repository\" />
    <Folder Include="ThirdPartyServices\" />
  </ItemGroup>

</Project>
